version: "3.9"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - type: bind
        source: restapi
        target: /app
    ports:
      - "8000:8000"